// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcRootApiOutputTypes = { proc_name: "test_error"; output_type: boolean } | { proc_name: "perm_ctlr_connect"; output_type: boolean } | { proc_name: "set_permeability"; output_type: null }

export type TauRpcEventsInputs = { proc_name: "ev"; input_type: string }

export type TauRpcRootApiInputs = { proc_name: "test_error"; input_type: string } | { proc_name: "perm_ctlr_connect"; input_type: string } | { proc_name: "set_permeability"; input_type: [number, number] }

export type TauRpcEventsOutputTypes = { proc_name: "ev"; output_type: null }


import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>()

type Router = {
	'': [TauRpcRootApiInputs, TauRpcRootApiOutputTypes],
	'events': [TauRpcEventsInputs, TauRpcEventsOutputTypes],
}